import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import herobanner from '../public/herobanner.jpg'
import { Link, DirectLink, Element, Events, animateScroll as scroll, scrollSpy, scroller } from 'react-scroll'
import Navbar from '../pages/navbar.js'
import Hero from '../pages/hero.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tayte Bitton Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <main className="px-10">
      </main>
    </div>
  )
}
