import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import tayte from '../public/2.jpg'
import { Link, DirectLink, Element, Events, animateScroll as scroll, scrollSpy, scroller } from 'react-scroll'
import {Navbar} from '../pages/navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10">
        <section className="h-screen">

          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-3xl font-Monsterrat-Bold">Tayte</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li><a className="bg-gradient-to-r from-slate-400 via-slate-300 to-slate-400 bg-slate-300 text-black e0e px-4 py-2 rounded border-none ml-8 font-MontserratMedium" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-white">Tayte Bitton</h2>
            <h3 className="text-2xl py-2 font-MonserratLightItalic">Developer and designer.</h3>
          <p className="text-md py-5 leading-8">
            17 year old developer wanting to take my hobbies to a professional level. You are viewing a website created with React.js and Tailwindcss as an example of my work. 
          </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-slate-400">
            <a href="https://github.com/taytey/Portfolio-Website"><AiFillGithub/></a>   
          </div>
          <div className="relative rounded-full w-80 h-80 mt-20">
            
          </div>
        </section>
      </main>
    </div>
  )
}
