import Head from 'next/head'
import Navbar from '../pages/navbar.js'
import Splash from './splash'

export default function Home() {
  return (
    <div className='scroll-smooth'>
      <Head>
        <title>Tayte Bitton Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10">
        <Navbar />
        <Splash />
      </main>
  </div>
  )
}